apiVersion: v1
kind: Namespace
metadata:
  name: slim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slim-config
  namespace: slim
data:
  config.yaml: |
    tracing:
      log_level: debug
      display_thread_names: true
      display_thread_ids: true
    runtime:
      n_cores: 0
      thread_name: "slim-data-plane"
      drain_timeout: 10s
    services:
      slim/0:
        nodeId: "slim-node-0"
        dataplane:
          servers:
            - endpoint: "0.0.0.0:46357"
              tls:
                insecure: true
          clients: []
        controller:
          servers:
            - endpoint: "0.0.0.0:46358"
              tls:
                insecure: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slim
  namespace: slim
  labels:
    app.kubernetes.io/name: slim
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slim
  template:
    metadata:
      labels:
        app.kubernetes.io/name: slim
    spec:
      containers:
      - name: slim
        image: ghcr.io/agntcy/slim:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/slim"]
        args: ["--config", "/etc/slim/config.yaml"]
        ports:
        - containerPort: 46357
          name: data
          protocol: TCP
        - containerPort: 46358
          name: control
          protocol: TCP
        env:
        - name: SLIM_SVC_ID
          value: "slim-node-0"
        volumeMounts:
        - name: config
          mountPath: /etc/slim
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: slim-config
---
apiVersion: v1
kind: Service
metadata:
  name: slim
  namespace: slim
spec:
  type: ClusterIP
  ports:
  - port: 46357
    targetPort: 46357
    protocol: TCP
    name: data
  - port: 46358
    targetPort: 46358
    protocol: TCP
    name: control
  selector:
    app.kubernetes.io/name: slim

