apiVersion: v1
kind: Pod
metadata:
  name: translator-travis
  labels:
    app: guessing-game
    role: translator
spec:
  containers:
  - name: translator
    image: slim-guessing-game:latest
    imagePullPolicy: Never
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
    envFrom:
      - secretRef:
          name: game-env
    command: ["guessing-game", "translator"]
    args:
      - "--agent-name=Travis"
      - "--target-language=Hungarian"
      - "--slim={\"endpoint\":\"http://slim.slim.svc.cluster.local:46357\",\"tls\":{\"insecure\":true}}"
      - "--shared-secret=secret123"
      - "--game-channel=classroom/guessing-game"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  restartPolicy: Never

